window.NAXOS4_COURSES = [
  {
    id: 'bricklayer-st0095',
    title: 'Bricklayer',
    standard: 'ST0095',
    version: '1.2',
    photoCount: 6,
    units: [
      ['Unit 1','S12: Apply joint finishes: For example, half round, flush, weather struck and recessed.','K17: Joint finishes: Half round, flush, weather struck and recessed.','S2: Identify and use personal protective equipment (PPE).','K2: Safety control equipment and how to use personal protective equipment (PPE).','S14: Gauge and hand mix mortar to ratio.','K20: Mixing Mortar: Ratios, silos, pre-mixed, gauging, hand mixing and mechanical mixing.','K18: Principles of basic decorative walling and piers: projecting and contrasting brick, isolated and attached pier, banding.','B3: Take ownership of given work.'],
      ['Unit 2','S10: Set out brick and block cavity wall to given tolerances, including an opening.','K21: Cavity wall setting out techniques: Bricks and blocks, openings and levels, use of profiles, gauge rods and squares.','S1: Comply with health and safety regulations, standards, and guidance.','K1: Control of Substances Hazardous to Health (CoSHH).Provision and use of work equipment regulations (PUWER) and Electrical safety. Health and Safety at Work Act. Manual handling','S6: Estimate and select required resources: For example, the quantity of bricks and blocks, mortar, wall ties and insulation.','K12: Simple resource estimation techniques: Quantity of bricks and blocks, amount of mortar, quantity of wall ties, DPCs, cavity trays and lintels.','K8: Materials and their characteristics: Bricks and blocks, efflorescence, mortar, damp proof courses (DPC), wall ties, plasticisers, concrete and steel lintels, Rolled Steel Joist (RSJ), fire stopping, insulation, cement and building sand.','B5: Seek learning and development opportunities.'],
      ['Unit 3','S11: Construct a stretcher bond brick and block cavity wall with return and opening to given tolerances,','K22: Cavity wall construction using stretcher bond brick and block walling, forming openings,','S1: Comply with health and safety regulations, standards, and guidance.','K1: Awareness of health and safety regulations, standards, and guidance and impact on role.','S8: Select and use hand tools. S9: Maintain and store hand tools.','K13: Hand tool use, maintenance and storage: Levels, measures, hammers, bolsters, brick hammers, trowels, brick jointer, line blocks and pins, scutch, chariot and brick clamps.','K6: Principles of building: Foundations, roofs, walls, cavity step trays, floors, utilities and services, insulation, fire, moisture and air protection, damp proof courses, the use of brick ties and quality of materials.','B5: Seek learning and development opportunities.'],
      ['Unit 4','S11: including installing a lintel with soldiers,','K22: lintels','S1: Comply with health and safety regulations, standards, and guidance.','K1: Situational awareness. Slips, trips, and falls.','S18: Verbally communicate with others, applying construction terminology.','K26: Verbal communication techniques and construction terminology.','K27: Principles of good team working.','B6: Team-focus to meet team goals including, considering the wider build team.'],
      ['Unit 5','S11: brick and edge sill, closure around opening,','K22: closing cavities. selection and placement of wall ties,','S4: Comply with industry regulations, standards, and guidance.','K7: Standards and regulations associated with bricklaying activities: British standards, building regulations and warranty provider standards.','S19: Follow equity, diversity and inclusion guidance.','K28: Inclusion, equity and diversity in the workplace.','K19: Principles of the use of expansion joints. K9: Modern methods of construction: Rapid build technology, precast components, corner profiles, alternative frame and cladding systems, masonry support systems.','B4: Contribute to an inclusive and diverse culture.'],
      ['Unit 6','S11: insulation, fire stopping,','K22: insulation, fire stopping.','S1: Comply with health and safety regulations, standards, and guidance.','K1: Fire safety, fire extinguishers','S21: Identifies well-being support available to self and others.','K31: Well-being: Mental and physical health considerations in self and others and how to access support.','K5: The importance and considerations of the environment and sustainability: Thermal qualities, airtightness and ventilation in buildings.','B1: Put health, safety and wellbeing first.'],
      ['Unit 7','S11: cavity tray, damp proof course (DPC) and weep holes.','K22: damp proof courses (DPCs), cavity trays, weep holes,','S1: Comply with health and safety regulations, standards, and guidance.','K1: signage, Safety signage.','S17: Protect materials and finished work.','K25: Methods of protecting materials and work: Frost, water and construction damage.','K11: Basic principles of digital design and modelling systems.','B1: Put health, safety and wellbeing first.'],
      ['Unit 8','S13: Set out and construct a simple brick solid wall with capping.','K16: Brick solid wall setting out, construction and capping methods.','S5: Read and interpret information from drawings and specifications.','K10: Methods of interpreting and extracting relevant information from drawings and specifications.','S3: Comply with environmental and sustainability regulations, standards, and guidance. Segregate resources for reuse, recycling and disposal.','K4: Impact of the sector on the environment: Efficient use of resources. Recycling, reuse, surface water contamination and safe disposal of waste.','K15: Bond types: English bond, flemish bond, garden wall bonds and broken bond.','B2: Consider the environment when using resources and carrying out processes.'],
      ['Unit 9','S16: Carry out a simple repair: For example, replacing damaged bricks.','K24: Defects and repair: Construction defects and repair methods.','S1: Comply with health and safety regulations, standards, and guidance.','K1: Asbestos awareness.','S7: Prepare and maintain a safe working area.','K3: Safe systems of work: Site inductions, toolbox talks, risk assessments, method statements and hazard identification in the work area.','S20: Applies team working principles to their own and the wider build team.','B2: Consider the environment when using resources and carrying out processes.'],
      ['Unit 10','S22: Construct a brick wall with raking cut. For example, gable end wall or garden wall with raking cut.','K30: Brick walls with raking cut: Setting out and construction techniques.','S1: Comply with health and safety regulations, standards, and guidance.','K1: Working in confined spaces. Working at height.','S15: Measure and cut bricks and blocks using hand tools, to given tolerances.','K29: Methods of cutting bricks and blocks using hand tools.','K14: Power tool use and limitations: Disc cutters, mixers and drills.','B3: Take ownership of given work.']
    ]
  },
  {
    id: 'architectural-joiner-st0264',
    title: 'Architectural Joiner',
    standard: 'ST0264',
    version: '1.4',
    photoCount: 6,
    units: [
      ['Unit 1','S24: Architectural joiner: Produce basic woodworking joints including dovetail, bridal, mortise and tenon and halving.','K33: Architectural joiner: Timber joints, types and production techniques: Dovetails, mortise and tenon, bridals and halvings.','S1: Comply with health and safety regulations, standards, and guidance.','K1: Awareness of health and safety regulations, standards, and guidance and impact on role.','S25: Architectural joiner: Form connections using dowels, biscuit, staples and adhesives.','K35: Architectural joiner: Connection methods in joinery: Dowels, biscuit, staples and adhesives.','K9: Materials and their characteristics of home grown and imported timber and timber-based products','B1: Put health, safety and wellbeing first.'],
      ['Unit 2','S26: Architectural joiner: Apply techniques and practices to the manufacture and assembly of a timber window with casement including glazing rebates and associated ironmongery.','K34: Architectural joiner: Manufacture and assembly techniques for standard right angled timber windows.','S1: Comply with health and safety regulations, standards, and guidance.','K1: Asbestos awareness.','S6: Interpret and use information from drawings and specifications.','K8: Methods of interpreting and extracting relevant information from drawings and specifications.','K6: Basic principles of digital design and modelling systems','B2: Consider the environment when using resources and carrying out processes.'],
      ['Unit 3','S27: Architectural joiner: Apply manufacture and assembly techniques for first fix products: 1. straight staircases,','K36: Architectural joiner: Manufacture and assembly techniques for timber first fix products: 1. straight staircases','S1: Comply with health and safety regulations, standards, and guidance.','K1: Working in confined spaces. Working at height.','S7: Estimate required materials and produce a cutting list.','K12: Basic material estimation techniques, calculating lengths of timber, fixing requirements and a cutting list production methods.','K13: Verbal communication techniques and construction terminology. S8: Verbally communicate with others, applying construction terminology.','B3: Contribute to an inclusive and diverse culture.'],
      ['Unit 4','S27: Architectural joiner: Apply manufacture and assembly techniques for first fix products: 2. door frames and linings.','K36: Architectural joiner: Manufacture and assembly techniques for timber first fix products: 2. door frames and linings.','S1: Comply with health and safety regulations, standards, and guidance.','K1: signage, Safety signage.','S11: Maintain and sharpen hand tools.','K15: Hand tool maintenance and sharpening techniques.','K10: Timber decay and repair methods','B4: Seek learning and development opportunities.'],
      ['Unit 5','S28: Architectural joiner: Apply manufacture and assembly techniques for second fix products: 1. timber doors,','K37: Architectural joiner: Manufacture and assembly techniques for second fix timber products: 1. timber wall and floor units','S1: Comply with health and safety regulations, standards, and guidance.','K1: Control of Substances Hazardous to Health (CoSHH).Provision and use of work equipment regulations (PUWER) and Electrical safety. Health and Safety at Work Act. Manual handling','S10: Select, use and store power tools.','K17: Power tools use and storage methods and techniques: Portable circular saws, drills, saws, planers, routers, sanders, multi-functional tools and nail guns.','K40: Employment types, small business start up principles and tax','B5: Team-focus to meet team goals including, considering the wider build team.'],
      ['Unit 6','S28: Architectural joiner: Apply manufacture and assembly techniques for second fix products:2. wall and floor units,','K37: Architectural joiner: Manufacture and assembly techniques for second fix timber products: 2. timber doors','S2: Identify and use safety control equipment, for example, RPE, dust suppression, PPE and LEV.','K2: Safety control equipment and how to use personal protective equipment (PPE) respiratory protective equipment (RPE) and local exhaust ventilation (LEV).','S23: Architectural joiner: Produce setting out details, including setting rods, and mark out for timber products.','K32: Architectural joiner: Setting out and marking out techniques for joinery product manufacture and potential effects of marking out errors.','K30: Requirements of fire door assemblies','B1: Put health, safety and wellbeing first.'],
      ['Unit 7','S28: Architectural joiner: Apply manufacture and assembly techniques for second fix products: 3. timber mouldings,','K37: Architectural joiner: Manufacture and assembly techniques for second fix timber products: 3. timber mouldings.','S3: Comply with environmental and sustainability regulations, standards, and guidance. Segregate resources for reuse, recycling and disposal.','K4: Impact of the sector on the environment: Efficient use of resources. Recycling, reuse, safe disposal of waste and sustainable forestry.','S13: Identifies well-being support available to self and others.','K20: Well-being: Mental and physical health considerations in self and others and how to access support.','K38: Finishing techniques for manufactured timber products','B2: Consider the environment when using resources and carrying out processes.'],
      ['Unit 8','S28: Architectural joiner: Apply manufacture and assembly techniques for second fix products: 4. staircase spindles and balustrades.','K37: Architectural joiner: Manufacture and assembly techniques for second fix timber products: 4. staircase spindles and balustrades.','S1: Comply with health and safety regulations, standards, and guidance.','K1: Situational awareness. Slips, trips, and falls.','S12: Produce jigs.','K16: Jig production techniques.','K18: Principles of good team working','B3: Contribute to an inclusive and diverse culture.'],
      ['Unit 9','S29: Architectural joiner: Fit ironmongery including door locks, door handles, door hinges, latches and draw runners.','K39: Architectural joiner: Ironmongery installation techniques.','S4: Comply with industry regulations, standards, and guidance.','K7: Standards and regulations associated with carpentry activities: British standards, building regulations and warranty provider standards.','S9: Select, use and store hand tools.','K14: Hand tool use and storage methods and techniques: Chisels, planes, hand saws, hammers, squares, tri-square, bevels, marking and mortise gauges, spirit levels.','K19: Inclusion, equity and diversity in the workplace','B4: Seek learning and development opportunities.'],
      ['Unit 10','S30: Architectural joiner: Inspect, prepare and operate fixed machinery.','K31: Architectural joiner: Safe use of fixed machinery, inspection, preparation and operation techniques: Crosscut saw, band saw, planer and thicknesser and mortiser.','S1: Comply with health and safety regulations, standards, and guidance.','K1: Fire safety, fire extinguishers','S5: Prepare and maintain a safe working area.','K3: Safe systems of work: Site inductions, tool box talks, risk assessments, method statements and hazard identification in the work area.','K5: Principles of building and modern methods of construction','B5: Team-focus to meet team goals including, considering the wider build team.']
    ]
  },
  {
    id: 'site-carpenter-st0264',
    title: 'Site Carpenter',
    standard: 'ST0264',
    version: '1.4',
    photoCount: 5,
    units: [
      ['Unit 1','S14: Site carpenter: Apply first fix techniques and practices for: 1. structural carcassing (load bearing studwork)','K27: Site carpentry: First fixing installation techniques: Structural carcassing (load bearing studwork)','S1: Comply with health and safety regulations, standards, and guidance.','K1: Awareness of health and safety regulations, standards, and guidance and impact on role.','S10: Select, use and store power tools.','K17: Power tools use and storage methods and techniques: Portable circular saws, drills, saws, planers, routers, sanders, multi-functional tools and nail guns.','K9: Materials and their characteristics of home grown and imported timber and timber-based products','B1: Put health, safety and wellbeing first.'],
      ['Unit 2','S14: Site carpenter: Apply first fix techniques and practices for: 2. straight timber or metal partition walls,','K27: Site carpentry: First fixing installation techniques: metal and timber stud partitions.','S19: Site carpenter: Use and store laser levels for example cross line laser.','K29: Site carpentry: Types, use, calibration and storage of laser levels.','S16: Site carpenter: Size timber from sizing tables.','K23: Site Carpenter: Timber sizing tables purpose and use.','K5: Principles of building and modern methods of construction','B4: Seek learning and development opportunities.'],
      ['Unit 3','S14: Site carpenter: Apply first fix techniques and practices for: 3. floor joists, 4. floor joist coverings','K27: Site carpentry: First fixing installation techniques: floor joists and coverings','S1: Comply with health and safety regulations, standards, and guidance.','K1: Control of Substances Hazardous to Health (CoSHH).Provision and use of work equipment regulations (PUWER) and Electrical safety. Health and Safety at Work Act. Manual handling','S15: Site carpenter: Install structural fixings.','K22: Site carpentry: Structural fixtures and timber sizing in site carpentry, how to use sizing tables.','K10: Timber decay and repair methods','B2: Consider the environment when using resources and carrying out processes.'],
      ['Unit 4','S14: Site carpenter: Apply first fix techniques and practices for: 5. straight flights of stairs.','K27: Site carpentry: First fixing installation techniques: straight flights of stairs','S1: Comply with health and safety regulations, standards, and guidance.','K1: Situational awareness. Slips, trips, and falls.','S6: Interpret and use information from drawings and specifications.','K8: Methods of interpreting and extracting relevant information from drawings and specifications.','K6: Basic principles of digital design and modelling systems','B1: Put health, safety and wellbeing first.'],
      ['Unit 5','S17: Site carpenter: Apply site second fix techniques and practices for: 1. service encasement,','K28: Site carpentry: Second fix installation techniques: Service encasement,','S1: Comply with health and safety regulations, standards, and guidance.','K1: Fire safety, fire extinguishers','S9: Select, use and store hand tools.','K14: Hand tool use and storage methods and techniques: Chisels, planes, hand saws, hammers, squares, tri-square, bevels, marking and mortise gauges, spirit levels.','S13: Identifies well-being support available to self and others.','B3: Contribute to an inclusive and diverse culture.'],
      ['Unit 6','S17: Site carpenter: Apply site second fix techniques and practices for: 2. cladding','K28: Site carpentry: Second fix installation techniques: cladding,','S1: Comply with health and safety regulations, standards, and guidance.','K1: Asbestos awareness.','S5: Prepare and maintain a safe working area.','K3: Safe systems of work: Site inductions, tool box talks, risk assessments, method statements and hazard identification in the work area.','K20: Well-being: Mental and physical health considerations in self and others','B1: Put health, safety and wellbeing first.'],
      ['Unit 7','S17: Site carpenter: Apply site second fix techniques and practices for: 3. wall and floor units and fitments,','K28: Site carpentry: Second fix installation techniques: wall and floor units and fitments','S3: Comply with environmental and sustainability regulations, standards, and guidance. Segregate resources for reuse, recycling and disposal.','K4: Impact of the sector on the environment: Efficient use of resources. Recycling, reuse, safe disposal of waste and sustainable forestry.','S12: Produce jigs.','K16: Jig production techniques.','K18: Principles of good team working','B5: Team-focus to meet team goals including, considering the wider build team.'],
      ['Unit 8','S17: Site carpenter: Apply site second fix techniques and practices for: 4. handrails and spindles to straight flights of stairs,','K28: Site carpentry: Second fix installation techniques: handrails and spindles to straight flights of stairs,','S1: Comply with health and safety regulations, standards, and guidance.','K1: signage, Safety signage.','S8: Verbally communicate with others, applying construction terminology.','K13: Verbal communication techniques and construction terminology.','K38: Finishing techniques for manufactured timber products','B4: Seek learning and development opportunities.'],
      ['Unit 9','S17: Site carpenter: Apply site second fix techniques and practices for: 5. internal and external doors,','K28: Site carpentry: Second fix installation techniques: doors','S20: Site carpenter: Form connections, for example, using joints, nails, screws, bolts and adhesive.','K11: Carpentry and joinery products and purpose: Mastics, preservatives, wood fillers, plastics and ironmongery.','S11: Maintain and sharpen hand tools.','K15: Hand tool maintenance and sharpening techniques.','K30: Requirements of fire door assemblies','B1: Put health, safety and wellbeing first.'],
      ['Unit 10','S17: Site carpenter: Apply site second fix techniques and practices for: 6. skirting boards and architrave,','K28: Site carpentry: Second fix installation techniques: mouldings (architrave and skirting board).','S2: Identify and use safety control equipment, for example, RPE, dust suppression, PPE and LEV.','K2: Safety control equipment and how to use personal protective equipment (PPE) respiratory protective equipment (RPE) and local exhaust ventilation (LEV).','S22: Site carpenter: Carrying out splicing and scribing techniques.','K24: Site carpentry: Timber splicing and scribing techniques.','K40: Employment types, small business start up principles and tax','B2: Consider the environment when using resources and carrying out processes.'],
      ['Unit 11','S17: Site carpenter: Apply site second fix techniques and practices for: 7. window boards.','K28: Site carpentry: Second fix installation techniques: window boards','S4: Comply with industry regulations, standards, and guidance.','K7: Standards and regulations associated with carpentry activities: British standards, building regulations and warranty provider standards.','S21: Site carpenter: Apply measuring, marking out, cutting (square and angled), mitring, hinging and recessing techniques.','K21: Site carpentry techniques: Measuring, marking out, fitting, cutting (straight and angled) and mitring.','K19: Inclusion, equity and diversity in the workplace','B3: Contribute to an inclusive and diverse culture.'],
      ['Unit 12','S18: Site carpenter: Apply site carpenter techniques and practices to construction of rafter roofs, including trussed (prefabricated) and traditional (built on site) including the construction of verge, eaves and fitting loft access.','K25: Site carpentry: Straight roof installation techniques: Basic rafter trussed (prefabricated) and traditional cut roof (built on site).','S1: Comply with health and safety regulations, standards, and guidance.','K1: Working in confined spaces. Working at height.','S7: Estimate required materials and produce a cutting list.','K12: Basic material estimation techniques, calculating lengths of timber, fixing requirements and a cutting list production methods.','K26: Flat roofs: Warm and cold flat roofs including firings and coverings','B5: Team-focus to meet team goals including, considering the wider build team.']
    ]
  }
].map(c => ({
  ...c,
  units: c.units.map(r => ({unit:r[0], A:r[1], B:r[2], C:r[3], D:r[4], E:r[5], F:r[6], G:r[7], H:r[8]}))
}));
